import Header from './components/Header'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Nextjs13',
  description: 'Generated by create next app',
  keywords: 'web, nextjs, github, repositories',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <main class="container">{children}</main>
      </body>
    </html>
  )
}
